const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Keyboard,
		C3.Plugins.Sprite,
		C3.Behaviors.DragnDrop,
		C3.Behaviors.Pin,
		C3.Plugins.Mouse,
		C3.Plugins.Button,
		C3.Plugins.TextBox,
		C3.Plugins.TiledBg,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.TiledBg.Acts.SetVisible,
		C3.Plugins.Button.Acts.SetVisible,
		C3.Plugins.TextBox.Acts.SetVisible,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.TextBox.Acts.SetText,
		C3.Plugins.TextBox.Cnds.OnClicked,
		C3.Plugins.TextBox.Cnds.CompareText,
		C3.Behaviors.DragnDrop.Acts.SetEnabled,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.SetVar,
		C3.Behaviors.DragnDrop.Cnds.OnDragStart,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.CompareVar
	];
};
self.C3_JsPropNameTable = [
	{Teclado: 0},
	{ATX_Case: 0},
	{ArrastrarYSoltar: 0},
	{Pegado: 0},
	{CPU: 0},
	{CPU_Cooler: 0},
	{Gráfica: 0},
	{Placa_Base: 0},
	{Fuente_Alimentación: 0},
	{RAM: 0},
	{Mouse: 0},
	{Start: 0},
	{CPU_pregunta: 0},
	{FondoEnMosaico: 0},
	{Titulo_GAME1: 0},
	{CPE_Cooler_Pregunta: 0},
	{RAM_Pregunta: 0},
	{Fuente_Alimentación_Pregunta: 0},
	{Placa_base_pregunta: 0},
	{Gráfica_pregunta: 0},
	{CPU_Solucion: 0},
	{CPU_Cooler_Solucion: 0},
	{RAM_Solucion: 0},
	{Placa_Base_Solucion: 0},
	{Grafica_Solucion: 0},
	{Fuente_Alimentacion_Solucion: 0},
	{PlaceHolder_Placa_Base: 0},
	{Placa_Base_Placeholder: 0},
	{CPU_Placeholder: 0},
	{CPU_Cooler_Placeholder: 0},
	{RAM_Placeholder: 0},
	{Grafica_Placeholder: 0},
	{Fuente_Alimentacion_Placeholder: 0},
	{Aciertos: 0},
	{Contador: 0},
	{Restart: 0},
	{MenúRestart: 0},
	{Acabar_juego: 0},
	{Puntaje: 0}
];

self.InstanceType = {
	Teclado: class extends self.IInstance {},
	ATX_Case: class extends self.ISpriteInstance {},
	CPU: class extends self.ISpriteInstance {},
	CPU_Cooler: class extends self.ISpriteInstance {},
	Gráfica: class extends self.ISpriteInstance {},
	Placa_Base: class extends self.ISpriteInstance {},
	Fuente_Alimentación: class extends self.ISpriteInstance {},
	RAM: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Start: class extends self.IButtonInstance {},
	CPU_pregunta: class extends self.ITextInputInstance {},
	FondoEnMosaico: class extends self.ITiledBackgroundInstance {},
	Titulo_GAME1: class extends self.ITextInputInstance {},
	CPE_Cooler_Pregunta: class extends self.ITextInputInstance {},
	RAM_Pregunta: class extends self.ITextInputInstance {},
	Fuente_Alimentación_Pregunta: class extends self.ITextInputInstance {},
	Placa_base_pregunta: class extends self.ITextInputInstance {},
	Gráfica_pregunta: class extends self.ITextInputInstance {},
	CPU_Solucion: class extends self.ITextInputInstance {},
	CPU_Cooler_Solucion: class extends self.ITextInputInstance {},
	RAM_Solucion: class extends self.ITextInputInstance {},
	Placa_Base_Solucion: class extends self.ITextInputInstance {},
	Grafica_Solucion: class extends self.ITextInputInstance {},
	Fuente_Alimentacion_Solucion: class extends self.ITextInputInstance {},
	PlaceHolder_Placa_Base: class extends self.ISpriteInstance {},
	Placa_Base_Placeholder: class extends self.ISpriteInstance {},
	CPU_Placeholder: class extends self.ISpriteInstance {},
	CPU_Cooler_Placeholder: class extends self.ISpriteInstance {},
	RAM_Placeholder: class extends self.ISpriteInstance {},
	Grafica_Placeholder: class extends self.ISpriteInstance {},
	Fuente_Alimentacion_Placeholder: class extends self.ISpriteInstance {},
	Aciertos: class extends self.ITextInputInstance {},
	Contador: class extends self.ITextInputInstance {},
	Restart: class extends self.IButtonInstance {},
	MenúRestart: class extends self.ISpriteInstance {},
	Acabar_juego: class extends self.IButtonInstance {}
}